# Generated by Django 4.2.9 on 2024-02-05 00:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import application.utils.customer_storage


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_comment="ID", primary_key=True, serialize=False
                    ),
                ),
                ("kana", models.CharField(db_comment="カナ氏名", max_length=255)),
                ("name", models.CharField(db_comment="氏名", max_length=255)),
                ("birthday", models.DateField(db_comment="誕生日")),
                (
                    "phone_no",
                    models.CharField(
                        blank=True,
                        db_comment="電話番号",
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9]{11}$", "11桁の数字を入力してください。"
                            )
                        ],
                    ),
                ),
            ],
            options={
                "db_table": "Customer",
                "db_table_comment": "お客様",
            },
        ),
        migrations.CreateModel(
            name="CustomerPhoto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_comment="ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        db_comment="写真",
                        storage=application.utils.customer_storage.CustomerStorage(),
                        upload_to="customer_photo",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        db_comment="お客様ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.customer",
                    ),
                ),
            ],
            options={
                "db_table": "CustomerPhoto",
                "db_table_comment": "お客様の画像",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "password",
                    models.CharField(max_length=128, verbose_name="password"),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        db_comment="ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "employee_number",
                    models.CharField(
                        db_comment="社員番号",
                        max_length=8,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator("^[0-9]{8}$")
                        ],
                        verbose_name="社員番号",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_comment="ユーザ名",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_comment="メールアドレス", max_length=254, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_comment="作成日"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="更新日"),
                ),
                (
                    "groups",
                    models.ForeignKey(
                        db_comment="社員権限テーブル外部キー",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="auth.group",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "User",
                "db_table_comment": "システムユーザ",
                "ordering": ["employee_number"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
