# Generated by Django 4.2.9 on 2024-02-04 04:53

from django.db import migrations

import application.managers


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", application.managers.UserManager()),
            ],
        ),
    ]
