# Generated by Django 4.2.9 on 2024-02-04 04:53

import application.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", application.managers.UserManager()),
            ],
        ),
    ]
